### ISSUE TITLE
Is it possible to add a global search feature?

### ISSUE THREAD

**Issue by jizai** [yzs249175311/org-html-theme-dull#1]
The current theme will display an html file by title, at this time, if you use C-f to search in the browser, you can only search the content of the current page, not the content of the entire html file. Is there a way to add a search box to search the entire html document?

---------------------------------
当前主题会将一个html文件按照标题进行分栏显示，此时使用C-f在浏览器中搜索的话，只能搜索到当前主题页面的内容，而不是整个html文件的内容。是否有办法添加一个搜索框，用来搜索整个html文档的内容？

**Comment by yzs249175311** [comment]
相比于添加一个搜索框来搜索文本，其实提供一个方法把所有内容都展示出来让你搜索要更简单一点。

我一般一个org文件只会使用一个大的标题，所以所有内容都在一个页面上，我不太知道别人是怎么用的。

我会尝试写一个搜索功能，但是我不确定这会不会造成性能问题。

**Comment by jizai** [comment]
额，我的笔记目前都在一个org文件里，通过不同的大标题区分的，因为内容还不是太多，估计后续会和你一样，把每个大标题都拆分出来，那这个问题我就先关了

感谢热心回复！
