### ISSUE TITLE
动画效果问题

### ISSUE THREAD

**Issue by jizai** [yzs249175311/org-html-theme-dull#2]
提供的示例网页中，先点已读标题，然后鼠标滚轮向下滑动，就会看到页面不停地抖动。这个问题一直都存在，最新的提交好像也存在这个问题。

**Comment by yzs249175311** [comment]
不应该啊，我早就修复了，你用的什么浏览器？

**Comment by yzs249175311** [comment]
> 不应该啊，我早就修复了，你用的什么浏览器？

我知道什么问题了

**Comment by yzs249175311** [comment]
现在应该没问题了。

**Comment by jizai** [comment]
我用的火狐浏览器，最新提交确实没问题了，十分感谢
