### ISSUE TITLE
能否调整脚注的位置

### ISSUE THREAD

**Issue by YouLanjie** [yzs249175311/org-html-theme-dull#3]
如果我在org文件中添加了一些脚注(footnotes)，那么它们所指向的内容将会显示在正文的右侧，目录的左侧。

例如我使用该项目的 `example.org` 添加了脚注后的显示效果：
![image](https://user-images.githubusercontent.com/66255345/233622265-81aa4345-bc2d-491a-ba26-1364cea97571.png)

如果增长脚注的长度，那么正文内容将会变得阅读困难或者无法阅读：
![image](https://user-images.githubusercontent.com/66255345/233623223-cfc4aec2-dab3-4285-92f5-e972d43027de.png)

它会挤压内容和目录的空间。我希望能够调整脚注的位置，例如分开到不同的标题分栏内，或者直接归入到一个新的标题分栏内（不过那样似乎脚注的跳转功能将会失效）

谢谢

**Comment by yzs249175311** [comment]
实现下基本的显示，我把显示的地方放在左侧，这样查看脚注的时候页面不用跳，鼠标悬停也可以直接看脚注的内容。

欢迎体验和提出意见。
