### ISSUE TITLE
能否调整部分内容的显示效果？

### ISSUE THREAD

**Issue by YouLanjie** [yzs249175311/org-html-theme-dull#4]
这里有个小问题，当我在qoute内部添加图片时，图片的宽度将会超出显示的宽度，在src内部长度过长时也是如此。显示效果如下：
![image](https://user-images.githubusercontent.com/66255345/235158752-5dd85507-fb80-4f03-98e9-ba46bc59a03f.png)

如果能够恢复无主题时的左右的进度条（像下面）就挺好
![image](https://user-images.githubusercontent.com/66255345/235160641-10018fdf-1c3e-4ef3-80ab-9e4c1ae04890.png)
当然我也同时希望能够让src的类型能够固定在右上角而非随着进度条拖动

还有我希望能够为脚注和目录（下面会解释）添加额外的打开入口（按钮）。这样我可以在一些情况下使用脚注实现（长篇）内容的快速跳转，而目录在竖屏情况下则会被自动隐藏，但是找不到任何的打开入口，相当于是失去了目录的功能。

我还有一个小小的问题，在 `verse` 括出的内容没有特殊的显示效果，和正常的文字显示效果无异，我想问下这个格式是否需要特殊的效果显示。

谢谢。

**Comment by yzs249175311** [comment]
感谢反馈。
1. 现在过长的代码块的内容应该能正确显示了，并且src的类型应该能固定在右边上角了。
2. 目录现在不会在窗口缩小的时候隐藏，以前关闭是因为怕小窗口的时候目录占据过多空间，现在目录可以通过鼠标拖动改变大小，所以也没必要隐藏了。
3. 按我的理解，`verse`和`quote`应该不同，`quote`是有特殊含义的，毕竟`quote`生成的标签是`blockquote`,而`verse`只是普通的`div`，我觉得`verse`和`center`一样，只是为了控制文本的显示方式，所以我不打算做特殊的显示处理，我也不知道怎么处理。
4. 由于一篇文章可能需要引用同一个脚注多次，所以想实现通过脚注定义定位文章引用脚注的位置比较麻烦，可能需要比较好的显示方式，而且我觉得大多数人应该没有这个需求，毕竟这不是脚注的作用，不过我在写脚注的时候也考虑到了这点，由于实现起来麻烦，所以目前脚注只会跳转到第一个引用它的位置。未来可能会实现。
5. 我发现文章的缩进还是很有问题，我打算尝试解决一下这个问题，希望到时候你能关注一下。

**Comment by YouLanjie** [comment]
您好，在更新后发现我的图片尽管不在会超出范围，但仍旧产生了错位现象，经过简单的调整测试后，我发现了诱发该问题的两种情况：

1) 在quote中除了图片没有任何其他的文字信息（包括图片前或者后）
    正常情况下的图片：
    ![image](https://user-images.githubusercontent.com/66255345/235314765-7fcbbac5-c072-4a6e-8c80-8b943385f951.png)

    异常情况下的图片：
    ![image](https://user-images.githubusercontent.com/66255345/235314791-fa816717-524e-4132-99cc-d64994ae893b.png)

2) 在quote中的图片被设置了 `CAPTION` 属性
    异常图像：
![image](https://user-images.githubusercontent.com/66255345/235314933-1d20223e-6c09-4db0-9525-0a622423955a.png)

希望能够修复这一bug，谢谢。

**Comment by YouLanjie** [comment]
紧急补充一下，我发现了我的失误，第二条的触发条件应当为 _当图片的前一行（非空行）为注释_ ，在这种条件下就会触发bug。

我用F12查看了下显示有无异常的代码区别，显示错位时的图片会被独立分到一个dev块内，其class="figure"
![image](https://user-images.githubusercontent.com/66255345/235315726-04df0385-75f1-4617-9137-e6eb22a48648.png)
而没有这个问题时图片则是和文字同处于一块 `<p></p>` 内部。（似乎注释能起到将两片内容分开成不同的块里面的作用）
![image](https://user-images.githubusercontent.com/66255345/235315849-789fbeb5-9af1-4e42-bb75-113651fa384a.png)
希望这对于修复bug有点帮助（即使不需要）

**Comment by yzs249175311** [comment]
现在应该修复了，你看看。
