### ISSUE TITLE
能否将代码块的字体更改为使用等宽字体？

### ISSUE THREAD

**Issue by YouLanjie** [yzs249175311/org-html-theme-dull#5]
突然发现代码块的字体并非是等宽字体，而是非等宽字体，导致部分内容的对齐会出现一些问题，希望能够使用在代码块部分使用等宽字体显示。谢谢。

**Comment by yzs249175311** [comment]
已经改成等宽的了。

如果不满意，你可以用类似下面的方式使用自己喜欢的字体，把下面代码写到你的配置文件里：

```elisp
(setq org-html-head-extra "<style> 
                              @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap');
                              pre{font-family:\"Roboto Mono\"!important;} 
                           </style>")	
```

**Comment by YouLanjie** [comment]
现在我在绘制字符画时，发现代码块中的中文和英文并未实现对齐，中文字符会比英文字符显示稍窄些，导致无法对齐，所以希望能够再更改下中英文字体的大小设置，谢谢。

**Comment by yzs249175311** [comment]
换了，你看看能达到你的要求不。

**Comment by yzs249175311** [comment]
> 换了，你看看能达到你的要求不。

不行，出了点问题，我再试试。

**Comment by YouLanjie** [comment]
使用本地的setupfile显示正常。不过网页字体链接出现问题了。`/assets/org-html-theme-dull.otf`链接到了域名的根目录下导致没有办法正常显示。

**Comment by yzs249175311** [comment]
你现在看看效果怎么样
